package com.wso2telco.core.pcrservice.oauth;

import org.junit.Test;
import org.wso2.carbon.identity.oauth.stub.dto.OAuthConsumerAppDTO;

import junit.framework.TestCase;

/**
 * The class <code>OAuthTokenValidaterStubFactoryTest</code> contains tests for
 * the class {@link <code>OAuthTokenValidaterStubFactory</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 9/6/16 4:00 PM
 *
 * @author yasith
 *
 * @version $Revision$
 */
public class OAuthApplicationDataTest extends TestCase {
	
	@Test
	public void test() throws Exception{
		OAuthApplicationData applicationData = new OAuthApplicationData();
		
		OAuthConsumerAppDTO[] apps = applicationData.getApplicationData();
						
		for (OAuthConsumerAppDTO oAuthConsumerAppDTO : apps) {
			 
			String clientId = oAuthConsumerAppDTO.getOauthConsumerKey();
			String applicationName = oAuthConsumerAppDTO.getApplicationName();
			String callbackUrl = oAuthConsumerAppDTO.getCallbackUrl();
			
			System.out.println(applicationName + " : " + clientId + " : " + callbackUrl );
		}	
		
	}
	
	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public OAuthApplicationDataTest(String name) {
		super(name);
	}
	
    public static void main(String[] args) {
        new org.junit.runner.JUnitCore().run(OAuthApplicationData.class);
    }
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = com.wso2telco.core.pcrservice.oauth
 * package.sourceFolder = pcr-service/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = OAuthTokenValidaterStubFactoryTest
 * testClassType = OAuthTokenValidaterStubFactory
 */