package com.wso2telco.core.pcrservice.oauth;

import org.junit.Test;
import org.wso2.carbon.identity.oauth.stub.dto.OAuthConsumerAppDTO;

import junit.framework.TestCase;

/**
 * The class <code>OAuthTokenValidaterStubFactoryTest</code> contains tests for
 * the class {@link <code>OAuthTokenValidaterStubFactory</code>}
 *
 * @author yasith
 * @version $Revision$
 * @pattern JUnit Test Case
 * @generatedBy CodePro at 9/6/16 4:00 PM
 */
public class OAuthApplicationDataTest extends TestCase {

    @Test
    public void test() throws Exception {
        OAuthApplicationData applicationData = new OAuthApplicationData();
        String clientid = "qwwert";
        OAuthConsumerAppDTO apps = applicationData.getApplicationData(clientid);

    }

    /**
     * Construct new test instance
     *
     * @param name the test name
     */
    public OAuthApplicationDataTest(String name) {
        super(name);
    }

    public static void main(String[] args) {
        new org.junit.runner.JUnitCore().run(OAuthApplicationData.class);
    }
}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = false
 * methods = 
 * package = com.wso2telco.core.pcrservice.oauth
 * package.sourceFolder = pcr-service/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = OAuthTokenValidaterStubFactoryTest
 * testClassType = OAuthTokenValidaterStubFactory
 */